config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/create", to: "moves#create_home"
  resources :moves do
    resources :bids, only: %i[new edit update  create index]
  end
  resources :bids, only: [:show]

  patch '/companies/bids', to: 'bids#confirm', as: 'confirm_bid'
  patch 'moves/:move_id/bids/:id/hire', to: 'bids#hire', as: 'hire_bid'
  get "/bids", to: "bids#index", as: "bids"
  get "/clients", to: "moves#client_index", as: "client"
  get "/companies", to: "moves#company_index", as: "company"
  get "/companies/bids", to: "bids#index", as: "company_bids"
  post "/update_bid_status", to: "bids#update_bid_status"
  resources :company do
    resources :reviews, only: %i[new create edit delete update]
  end
  get "/company/:id", to: "company#show", as: "company_show"
  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end
      resources :bids, only: %i[ delete]

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :move
  belongs_to :company

  def confirm!
    update(status: "confirmed")
    move.update(status: "confirmed")
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  skip_forgery_protection

  def index
    @company = Company.find_by(user_id: current_user.id)
    if @company
      @bids = Bid.where(company_id: @company.id)
    else
      @move = Move.find(params[:move_id])
      @bids = Bid.where(move_id: @move.id)
      @hired = @move.status == "pending" && @bids.where(status: "pending").count == 1
    end

    query = params[:query]
    if query.present? && query == "price"
      @bids = @bids.order(price: :desc)
    end
  end

  def show
    @bid = Bid.find(params[:id])
    @move = @bid.move
    @current_user = current_user
  end

  def hire
    @bid = Bid.find(params[:id])
    @move = @bid.move
    # Perform the necessary updates here
    # For example:
    @move.status = "pending"

    @bid.status = "pending"

    if @move.save! && @bid.save!
      redirect_to client_path, notice: "Bid hired successfully!"
    end
  end

  def update_bid_status
    # @move = Move.find(params[:move_id])
    @bid = Bid.find(params[:id])
    move = @bid.move

    p @bid.to_json
    p move.to_json

    if @bid.status == "pending"
      @bid.status = "confirmed"
      move.status = "confirmed"
      move.save!
      @bid.save!
    end
    @bids = Bid.where(move_id: move.id)

    respond_to do |format|
      format.html
      format.text {render partial: "bids/bids", locals: { bids: @bids}, formats: [:html]}
    end
  end

  def new
    @move = Move.find(params[:move_id])
    @bid = Bid.new
  end

  def create
    @bid = Bid.new(bid_params)
    @move = Move.find(params[:move_id])
    @bid.move_id = @move.id
    @company = Company.find_by(user_id: current_user.id)
    @bid.company_id = @company.id
    @bid.status = "open"
    @bid.expiration = false
    bids_generator
    if @bid.save!
      redirect_to company_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bid = Bid.find(params[:id])
    @move = Move.find(params[:move_id])
  end

  def update
    @bid = Bid.find(params[:id])
    if @bid.update(bid_params)
      redirect_to company_path, notice: 'Bid was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy
    redirect_to company_bids_path, notice: 'move was successfully destroyed'
  end

  private

  def bid_params
    params.require(:bid).permit(:price, :status, :expiration, :move_id, :company_id)
  end

  def bids_generator
    bid1 = Bid.create(price: 100,status: "open", expiration: false,move: @move,company_id: Company.find_by(user_id: User.find_by(first_name: "Emma").id).id)
    bid2 = Bid.create(price: 200,status: "open", expiration: false,move: @move,company_id: Company.find_by(user_id: User.find_by(first_name: "Josh").id).id)
    bid3 = Bid.create(price: 140,status: "open",expiration: false,move: @move,company_id: Company.find_by(user_id: User.find_by(first_name: "Zakarya").id).id)
    bid4 = Bid.create(price: 180,status: "open", expiration: false,move: @move,company_id: Company.find_by(user_id: User.find_by(first_name: "Pedro").id).id)
    bid5 = Bid.create(price: 120,status: "open", expiration: false,move: @move,company_id: Company.find_by(user_id: User.find_by(first_name: "Santi").id).id)
    bid1.save!
    bid2.save!
    bid3.save!
    bid4.save!
    bid5.save!
  end
end

app/views/bids/_bids.html.erb
    <div data-tabs-target="tab" id="one" >
      <div class="movescard" id="client-index" data-controller="hbutton">
        <% bids.where(status: "open").each do |bid|%>

          <div class="card" data-controller="popup" data-popup-id-value="<%= bid.id %>">
            <div id="indexcard" class="card-body">
              <div class="status-icon">
                <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= bid.status %></h6>
                  <div class="d-flex">
                  <h2><%= bid.price %> €</h2>
                </div>
              </div>
              <div id="indexcard" class="card-body">
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%d %b %Y") %>
                </h6>
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%l:%m %p") %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;">
                  </i> From: <%= bid.move.start_point %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-map-pin" style="color: #f66b0e;">
                  </i> To: <%= bid.move.end_point %>
                </h6>
              </div>
            </div>
          </div>

          <div id="<%= bid.id%>" data-status-target="bidid" data-bid="<%= bid.id%>"  class="d-none">
            <%= render "bids_show", bid: bid %>
          </div>

        <% end %>
      </div>
    </div>

    <div data-tabs-target="tab" id="two">
      <div class="movescard" id="client-index">
        <% bids.where(status: "pending").each do |bid|%>
          <div class="card" data-controller="popup" data-popup-id-value="<%= bid.id %>">
            <div id="indexcard" class="card-body">
              <div class="status-icon">
                <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= bid.status %> </h6>
                <div class="d-flex">
                  <h2><%= bid.price %> €</h2>
                </div>
              </div>
              <div id="indexcard" class="card-body">
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%d %b %Y") %>
                </h6>
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%l:%m %p") %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;">
                  </i> From: <%= bid.move.start_point %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-map-pin" style="color: #f66b0e;">
                  </i> To: <%= bid.move.end_point %>
                </h6>
                <% if !@confirmed %>
                  <button class="small_button_goal" data-action="click->status#update" data-bid="<%= bid.id%>" > Confirm</button>
                <% end %>
              </div>
            </div>
          </div>
          <div id="<%= bid.id%>" data-status-target="bidid" data-bid="<%= bid.id%>" class="d-none">
            <%= render "bids_show", bid: bid %>
          </div>
        <% end %>
      </div>
    </div>

    <div data-tabs-target="tab" id="three">
      <div class="movescard" id="client-index">
        <% bids.where(status: "confirmed").each do |bid|%>
          <div class="card" data-controller="popup" data-popup-id-value="<%= bid.id %>">
            <div id="indexcard" class="card-body">
              <div class="status-icon">
                <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= bid.status %></h6>
                  <div class="d-flex">
                  <h2><%= bid.price %> €</h2>
                </div>
              </div>
              <div id="indexcard" class="card-body">
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%d %b %Y") %>
                </h6>
                <h6 id="showcards" class="card-title">
                  <i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i>
                  <%= bid.move.date.strftime("%l:%m %p") %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;">
                  </i> From: <%= bid.move.start_point %>
                </h6>
                <h6 id="showcards" class="card-text">
                  <i class="iconmove fa-solid fa-map-pin" style="color: #f66b0e;">
                  </i> To: <%= bid.move.end_point %>
                </h6>
              </div>
            </div>
          </div>
          <div id="<%= bid.id%>" data-status-target="bidid" data-bid="<%= bid.id%>" class="d-none">
            <%= render "bids_show", bid: bid %>
          </div>
        <% end %>
      </div>
    </div>

app/views/bids/_bids_show.html.erb
  <h1 class="moves-text">My move</h1>
  <div class="container-full d-flex justify-content-center">
    <div class="container-full d-flex flex-wrap justify-content-center showcard">
      <div class="card col-8">
        <div id="showcards" class="card-body d-flex flex-column justify-content-between">
          <div class="d-flex justify-content-between">
            <div>
              <h5 id="showcards" class="card-title"><i class="iconmove fa-solid fa-building" style="color: #f66b0e;"></i><h6><%= Company.find(bid.company_id).name %></h5>
              <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-tag" style="color: #f66b0e;"></i><h6><%= bid.price %>€ </h5>
              <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-thumbs-up " style="color: #f66b0e;"></i><%= @rating %></h5>
              <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i><%= bid.created_at.strftime(" %d %b %Y ") %></h5>
              <h5 id="showcards" class="card-text"><i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i><%= bid.created_at.strftime("%l:%M %p") %></h5>
              <h5 id="showcards" class="card-text">
                <div class="move-status">
                  <% if bid.status == "open" %>
                    <i class="fa-solid fa-arrow-rotate-right"></i> <%= bid.status %>
                  <% elsif bid.status == "pending" %>
                    <i class="fa-solid fa-arrows-rotate fa-spin"></i> <%= bid.status %>
                  <% elsif bid.status == "confirmed" %>
                    <i class="fa-solid fa-square-check" style="color: #73c431;"></i> <%= bid.status %>
                  <% end %>
                </div>
            </div>
            <div>
              <h5 id="shipmenttext" class="card-text"><i class="iconmove fa-solid fa-circle-info"></i> Shipment Info:</h5>
              <p id="shipmenttext" class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed commodo sapien ut nunc rhoncus, et cursus dui lacinia.</p>
            </div>
          </div>
          <div class="d-flex justify-content-between">
            <%# <%= link_to "See received bids", move_bids_path(move.id), class: "small_button" %>
            <%# <%= link_to "Edit", edit_move_path(move.id), class: "small_button" %>
            <%# <%= link_to "", move_path(move.id), class: "order-3 btn btn-outline-danger text-light fa-solid fa-trash-can pt-2", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/bids/_company_bids.html.erb
<div class="container col-4 d-flex justify-content-center" data-controller="filter">
    <div class="col-6">
      <form novalidate="novalidate" class="filter-form simple_form" action="/bids" accept-charset="UTF-8" method="get">
        <select class="form-control string required" type="text" name="query" id="search_query" data-target="filter.select">
          <option value="rating">rating</option>
          <option value="price">price</option>
        </select>
        <div>
          <button name="button" type="submit" class="btn btn-flat" data-action="filter#applyFilter">
            <i class="fa-solid fa-filter"></i>
          </button>
        </div>
      </form>
    </div>
  </div>

  <h1 class="bids-text">My bids</h1>
  <div class="container-full" id="client-index">
    <div  data-controller="tabs" data-tabs-default-tab-value="two">
      <button id="one" class="small_button card-tab" data-tabs-target="btn " data-action="click->tabs#select">open</button>
      <button id="two" class="small_button " data-tabs-target="btn " data-action="click->tabs#select">pending</button>
      <button id="three" class="small_button " data-tabs-target="btn " data-action="click->tabs#select">confirmed</button>
      <div  class="container-full"  data-controller="status">
        <%= render "bids", bids: @bids %>
      </div>
    </div>
  </div>

app/views/bids/_form.html.erb
<div class="container d-flex justify-content-between mt-3 mb-3">
  <div class="small-card align-content-center" >
      <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i><%= @move.date.strftime("%d %b %Y") %></h5>
              <br>
      <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i><%= @move.date.strftime("%l:%m %p") %></h5>
            <br><h6>from</h6>
      <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i><%= @move.start_point %></h5>
            <br><h6 class="ml-1" >to</h6>
      <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= @move.end_point %></h5>
      <br>
      <h5 class="card-title"> <i class="fa-solid fa-arrows-rotate fa-spin"></i> <%= @move.status %></h5>
      <br>
      <h5 class="card-title"> <i class="fa-solid fa-circle-info"></i> <%= @move.shipment_info %></h5>
      <br>
      <%# <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <% if @move.expiration%>
      <%# </h5> %>
      <%= simple_form_for([@move, @bid]) do |f| %>
        <div class="card-body">
          <% company = Company.find_by(user_id: current_user) %>
          <% if @bid = @move.bids.find_by(company_id: company) %>
            <div>
              <h6>your bid</h6>
              <div class="d-flex">
                <h2><%= @bid.price %> €</h2>
            </div>

          <% else %>
            <h5 class="card-text"><%= f.input :price %></h5>
            <button company_path id="submitBtn" class="small_button_goal" type="submit">Place bid</button>
            <% end %>
          <% end %>
        </div>
  </div>
</div>
    <div class="right-container"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        <div id='map' style='width: 540px; height: 70vh;'></div>
          <script>
            mapboxgl.accessToken = 'pk.eyJ1IjoiZXN0aTI2IiwiYSI6ImNsaG9vMDF2cjFtMGozZHMxdmE0MnJrbzIifQ.SUs4-1vCL28RYJgPwDUFPA';
            const map = new mapboxgl.Map({
            container: 'map', // container ID
            style: 'mapbox://styles/mapbox/streets-v12', // style URL
            center: [-74.5, 40], // starting position [lng, lat]
            zoom: 9, // starting zoom
            });
            // const markers = <%= @markers.to_json %>; // Assuming @markers contains the coordinates of your instances

            // markers.forEach(marker => {
            //   new mapboxgl.Marker()
            //     .setLngLat(marker.coordinates) // Assuming the coordinates are in the format [longitude, latitude]
            //     .addTo(map);
          </script>
        </div>
    </div>
  </div>

app/views/bids/edit.html.erb
<h1>Edit your bid</h1>

<%= render "form" %>

app/views/bids/index.html.erb
<% if Company.find_by(user_id: current_user.id) %>

<%=  render "company_bids", bids: @bids %>

<% elsif Client.find_by(user_id: current_user.id) && @move.bids.present?%>
  <div class="d-flex justify-content-end mx-4">
     <%= link_to "Back to my moves", client_path(), class: "small_button" %>
    </div>
    <div class="container col-4 d-flex justify-content-center my-3" data-controller="filter">
    <div class="col-6">
      <form novalidate="novalidate" class="filter-form simple_form" action="/bids" accept-charset="UTF-8" method="get">
        <select class="form-control string required" type="text" name="query" id="search_query" data-target="filter.select">
          <option value="rating">rating</option>
          <option value="price">price</option>
        </select>
        <div>
          <button name="button" type="submit" class="btn btn-flat" data-action="filter#applyFilter">
            <i class="fa-solid fa-filter"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
  <h1 class="bids-text mt-0">My recieved bids</h1>
  <div class="container-full" id="client-index">
    <div  class="container-full">
      <div class="movescard" id="client-index" data-controller="hbutton">
        <% @move.bids.each do |bid| %>
          <div class="card" data-controller="popup" data-popup-id-value="<%= bid.id %>">
            <div id="indexcard" class="card-body">
              <div class="card-title-for-status">
                <h4 id="indexcard" ><i class="iconmove fa-solid fa-building " style="color: #f66b0e;"></i><%= Company.find(bid.company_id).name %></h4>
                <div class="status-icon">
                  <%if bid.status == "open"%>
                  <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= bid.status %></h6>
                  <%elsif bid.status = "pending"%>
                    <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= bid.status %> </h6>
                  <%elsif bid.status = "confirmed"%>
                    <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= bid.status %></h6>
                  <%end%>
                </div>
               </div>
                  <h5 id="indexcard" class="card-text"><i class="iconbid fa-solid fa-tag" style="color: #f66b0e;"></i><%= bid.price %>€ </h5>
                  <h5 id="indexcard" class="card-text"><i class="iconbid fa-solid fa-thumbs-up " style="color: #f66b0e;"></i><%= @rating ="⭐" * rand(1..5) %></h5>
                  <div class="d-flex justify-content-between" >
                    <a href="#" data-action="click->popup#open" class="small_button">See details</a>
                    <%= button_to "Hire", hire_bid_path(bid.move_id, bid.id), method: :patch, class: "hire-button small_button_goal", data: { action: "click->bid-hiring#hire" } if !@hired %>
                  </div>
                </div>
              </div>
              <div id="<%= bid.id%>" class="d-none">
                <%= render "bids_show", bid: bid %>
              </div>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
  <% else %>
    <div class="d-flex justify-content-end mx-4">
     <%= link_to "Back to my moves", client_path(), class: "small_button" %>
    </div>
    <h1 class="bids-text my-0">My recieved bids</h1>
  <div class="container d-flex justify-content-center"  >
    <div class="mb-5" id="client-empty-index">
      <h2>Oops! yet to receive bids. Please have patience!</h2>
    </div>
  </div>
<% end %>

app/views/bids/new.html.erb
<%= render "form" %>

app/views/bids/show.html.erb
<h1>Detail of the bid</h1>
<div class ="mx-5">
  <%= link_to "back to all bids", move_bids_path(@move.id), class: "small_button_back  mt-5" %>
</div>

<div class="small-card m-5" id="card-div">
          <%= link_to move_path(@move.id), data:{}, style:"text-decoration:none;", title: "show details of this move" do %>
          <div>
            <%if @move.status == "open"%>
              <h6 style="margin-left: 200px"> <i class="fa-solid fa-arrow-rotate-right"></i> <%= @move.status %></h6>
            <%elsif @move.status = "pending"%>
              <h6 style="margin-left: 200px"> <i class="fa-solid fa-arrows-rotate fa-spin"> </i> <%= @move.status %> </h6>
             <%elsif @move.status = "confirmed"%>
              <h6 style="margin-left: 200px"> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= @move.status %></h6>
              <%end%>
          </div>
          <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i>
            <%= @move.date.strftime("%d %b %Y") %></h5>
            <br>
          <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
            <%= @move.date.strftime("%l:%m %p") %></h5>
          <br><h6>from</h6>
          <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
            <%= @move.start_point %></h5>
          <br><h6 class="ml-1" >to</h6>
          <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= @move.end_point %></h5>
          <br><h6 class="ml-1" >Price</h6>
          <h5 class="card-title"> <i class="fa-solid fa-euro-sign"></i> <%= @bid.price %> € </h5>
          <% end %>
          <br>
          </div>