config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/create", to: "moves#create_home"
  resources :moves do
    resources :bids, only: %i[new edit update  create index]
  end
  resources :bids, only: [:show]

  patch '/companies/bids', to: 'bids#confirm', as: 'confirm_bid'
  patch 'moves/:move_id/bids/:id/hire', to: 'bids#hire', as: 'hire_bid'
  get "/bids", to: "bids#index", as: "bids"
  get "/clients", to: "moves#client_index", as: "client"
  get "/companies", to: "moves#company_index", as: "company"
  get "/companies/bids", to: "bids#index", as: "company_bids"
  post "/update_bid_status", to: "bids#update_bid_status"
  resources :company do
    resources :reviews, only: %i[new create edit delete update]
  end
  get "/company/:id", to: "company#show", as: "company_show"
  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end
      resources :bids, only: %i[ delete]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <h3 class="footer-h1">Easy Move In</h3> <br>
    <h4 class="footer-p">We make moving Fun</h4>
  </div>
  <div class= "f_text">
    <p class="footer-p">
      Register Moving Company <br>
      Affiliate Partner Program <br>
      FAQ – Frequently Asked Question <br>
      Cookie Settings
    </p>
  </div>
  <div>
    <p class="footer-p">Contact us :</p>
    <p class="footer-p">EasyMovein@gmail.com</p>
  </div>
  <%# <div class="footer-copyright">
  </div> %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "THELOGO.png", alt: "logo", class: "logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <i class="fa-solid fa-bell navbar-icon" style="color: #f66b0e; padding-right: 15px; sizes=16x16 32x32;"></i>
          <i class="fa-solid fa-message navbar-icon" style="color: #f66b0e; padding-right: 15px;"></i>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-user navbar-icon" style="color: #f66b0e; padding-right: 15px;"></i>
              <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if Client.find_by(user_id: current_user.id) %>
              <%= link_to "Dashboard", client_path, class: "dropdown-item" %>
              <% else %>
              <%= link_to "Dashboard", company_path, class: "dropdown-item" %>
            <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to company_path, id: "login", class: "nav-link " do %>
              <h4 class= "company">I am a Company &nbsp;&nbsp;&nbsp;</h4>
            <% end %>
          </li>
          <li>
            <%= link_to client_path, id: "login1", class: "nav-link " do %>
              <i class="fa-solid fa-circle-user" style="color: #f66b0e; font-size: 25px;"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>