config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/create", to: "moves#create_home"
  resources :moves do
    resources :bids, only: %i[new edit update  create index]
  end
  resources :bids, only: [:show]

  patch '/companies/bids', to: 'bids#confirm', as: 'confirm_bid'
  patch 'moves/:move_id/bids/:id/hire', to: 'bids#hire', as: 'hire_bid'
  get "/bids", to: "bids#index", as: "bids"
  get "/clients", to: "moves#client_index", as: "client"
  get "/companies", to: "moves#company_index", as: "company"
  get "/companies/bids", to: "bids#index", as: "company_bids"
  post "/update_bid_status", to: "bids#update_bid_status"
  resources :company do
    resources :reviews, only: %i[new create edit delete update]
  end
  get "/company/:id", to: "company#show", as: "company_show"
  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end
      resources :bids, only: %i[ delete]

end

app/models/move.rb
class Move < ApplicationRecord
  include PgSearch::Model
  belongs_to :client
  has_many :bids, dependent: :destroy
  geocoded_by :start_point
  after_validation :geocode, if: :will_save_change_to_start_point?
  pg_search_scope :search_by_shipment_info_and_address,
  against: [ :shipment_info, :start_point, :end_point ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: %i[show edit update destroy]

  def show
    @move = Move.find(params[:id])
    @moves = Move.all
    @next_move = Move.where(client_id: current_user.id).order(date: :asc).last
  end

  def new
    @move = Move.new
  end

  def create
    @move = Move.new(move_params)
    @move.client_id = current_user.id
    @move.status = "open"
    if @move.save
      redirect_to client_path, notice: 'moves was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create_home
    @move = Move.new(
      date: params[:date],
      start_point: params[:start_point],
      end_point: params[:end_point],
      shipment_info: params[:shipment_info]
)
    @move.client_id = current_user.id
    @move.status = "open"
    if @move.save
      redirect_to client_path, notice: 'moves was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @move.update(move_params)
      redirect_to client_path, notice: 'move was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @move.destroy
    redirect_to client_path, notice: 'move was successfully deleted'
  end

  def client_index
    @moves = Move.where(client_id: current_user)
    @next_move = @moves.where("date > ?", Time.now).first
    @moves = @moves.reject { |move| move.id == @next_move.id } if @moves.length > 1
    @user = User.find(current_user.id)
  end

  def company_index
    if params[:query].present?
      sql_query = <<~SQL
        moves.shipment_info ILIKE :query
        OR moves.start_point ILIKE :query
        OR moves.end_point ILIKE :query
      SQL
      @moves = Move.where(sql_query, query: "%#{params[:query]}%")
    else
      @moves = Move.all
    end
    @next_move = @moves.where("date > ?", Time.now).first


    if params[:filter] == "created"
      @moves = @moves.order(created_at: :desc)
    elsif params[:filter] == "earliest"
      @moves = @moves.order(date: :asc)
    end

    @markers = @moves.geocoded.map do |move|
      {
        lat: move.latitude,
        lng: move.longitude,
        info_window_html: render_to_string(partial: "moves/info_window", locals: { move: move }, formats: [:html]),
        marker_html: render_to_string(partial: "moves/marker", locals: { move: move }, formats: [:html])
      }
    end

    respond_to do |format|
      format.html
      format.text {render partial: "moves/results", locals: { moves: @moves, markers: @markers }, formats: [:html]}
    end
  end

  private

  def set_move
    @move = Move.find(params[:id])
  end

  def move_params
    params.require(:move).permit(:date, :start_point, :end_point, :shipment_info)
  end
end

app/views/moves/_bids_move_detail.html.erb
<h2>Details of the move</h2>
<div class="container-full d-flex justify-content-center">
  <div class="container-full d-flex flex-wrap justify-content-center showcard">
    <div>
      <div id="showcards" class="small-card card-body d-flex flex-column justify-content-between" style = "width:800px">
        <div class="container d-flex" style="justify-content: space-between;">
          <div class="move-status">
            <% if move.status == "open" %>
              <i class="fa-solid fa-arrow-rotate-right"></i> <%= move.status %>
            <% elsif move.status == "pending" %>
              <i class="fa-solid fa-arrows-rotate fa-spin"></i> <%= move.status %>
            <% else move.status == "confirmed" %>
              <i class="fa-solid fa-square-check" style="color: #73c431;"></i> <%= move.status %>
            <% end %>
          </div>
          <div>
            <% if !@next_move.nil? %>
              <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-times"></i>
              <% end %>
            <% end%>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div>
            <span id="showcards" class="card-text mb-3">
              <div class="popup">
              </span>
              <span id="showcards" class="card-title">
                <i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i>
                <%= move.date.strftime("%d %b %Y") %>
              </span>
              <span id="showcards" class="card-title">
                <i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i>
                <%= move.date.strftime("%l:%m %p") %>
              </span>
              <span id="showcards" class="card-text"><i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;"></i> From: <%= move.start_point %></span>
              <span id="showcards" class="card-text"><i class="iconmove fa-solid fa-map-pin" style="color: #f66b0e;"></i> To: <%= move.end_point %></span>
            </div>
          </div>
          <div>
            <div>
              <h5 id="shipmenttext" class="card-text"><i class="iconmove fa-solid fa-circle-info"></i> Shipment Info:</h5>
              <p id="shipmenttext" class="card-text"><%= move.shipment_info %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/moves/_companies.html.erb
  <div class="low-container">
    <div class="left-container">
      <div class="move-grid" id="move-grid">
       <%= render "results", moves: @moves %>
      </div>
    </div>
    <div class="right-container"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-controller="map"
      data-action="search:update@window->map#updateMap"
      data-map-markers-value="<%= @markers.to_json %>"
      id='map'
      style='width: 540px; height: 735px;'>
    </div>
  </div>

app/views/moves/_info_window.html.erb
<h2><%= move.date %></h2>
<p><%= move.start_point %></p>

app/views/moves/_results.html.erb
<div class="d-none" id="search-markers" data-marker="<%= @markers.to_json %>"></div>
<% moves.each do |move| %>
  <%if move.status = "open"%>
    <div class="small-card mb-5" id="card-div" data-controller="popup" data-popup-id-value="<%= move.id %>">
      <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #F66B0E"></i>
        <%= move.date.strftime("%d %b %Y") %></h5>
      <br>
      <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #F66B0E"></i>
        <%= move.date.strftime("%l:%m %p") %></h5>
      <br>
      <h6>from</h6>
      <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
        <%= move.start_point %></h5>
      <br>
      <h6 class="ml-1" >to</h6>
      <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= move.end_point %></h5>
      <br>
      <div class="link-container justify-content-between d-flex" data-controller="popup" data-popup-id-value="<%= move.id %>">
        <div class="d-flex justify-content-between">
          <a href="#" data-action="click->popup#open" class="small_button">See details</a>
        </div>
        <div id="<%= move.id %>" class="d-none">
          <%= render "show", move: move %>
        </div>
        <div><%= link_to "", new_chatroom_path, class: "btn fa-solid fa-envelope" %></div>
        <% company = Company.find_by(user_id: current_user) %>
        <% if bid = move.bids.find_by(company_id: company) %>
          <div>
            <h6>your bid</h6>
            <div class="d-flex">
              <h2><%= bid.price %> €</h2>
              <%= link_to "", edit_move_bid_path(move.id, bid.id), class: "btn text-light fa-solid fa-pen" %>
            </div>
          </div>
        <% else %>
          <%# <%= link_to "Bid", new_move_bid_path(move.id), class: "small_button_goal" %>
          <a href="#" data-action="click->popup#openbid" class="small_button_goal">Bid</a>
        </div>
        <div id="bidform<%= move.id %>" class="d-none">
          <%= render "bidform", bid: Bid.new , move: move %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="<%= move.id %>" class="d-none">
    <%= render "bids_move_detail", move: move %>
  </div>
<%end%>
<% end %>

app/views/moves/_show.html.erb
<h2>Details of the move</h2>
<div class="container-full d-flex justify-content-center">
  <div class="container-full d-flex flex-wrap justify-content-center showcard">
    <div>
      <div id="showcards" class="small-card card-body d-flex flex-column justify-content-between" style = "width:800px">
        <div class="container d-flex" style="justify-content: space-between;">
          <div class="move-status">
            <% if move.status == "open" %>
              <i class="fa-solid fa-arrow-rotate-right"></i> <%= move.status %>
            <% elsif move.status == "pending" %>
              <i class="fa-solid fa-arrows-rotate fa-spin"></i> <%= move.status %>
            <% else move.status == "confirmed" %>
              <i class="fa-solid fa-square-check" style="color: #73c431;"></i> <%= move.status %>
            <% end %>
          </div>
          <div>
            <% if !@next_move.nil? & Client.find_by(user_id: current_user.id)%>
              <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-times"></i>
              <% end %>
            <% end%>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div>
            <span id="showcards" class="card-text mb-3">
              <div class="popup">
              </span>
              <span id="showcards" class="card-title">
                <i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i>
                <%= move.date.strftime("%d %b %Y") %>
              </span>
              <span id="showcards" class="card-title">
                <i class="iconmove fa-regular fa-clock" style="color: #f66b0e;"></i>
                <%= move.date.strftime("%l:%m %p") %>
              </span>
              <span id="showcards" class="card-text"><i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;"></i> From: <%= move.start_point %></span>
              <span id="showcards" class="card-text"><i class="iconmove fa-solid fa-map-pin" style="color: #f66b0e;"></i> To: <%= move.end_point %></span>
            </div>
          </div>
          <div>
            <div>
              <h5 id="shipmenttext" class="card-text"><i class="iconmove fa-solid fa-circle-info"></i> Shipment Info:</h5>
              <p id="shipmenttext" class="card-text"><%= move.shipment_info %></p>
            </div>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <% if Client.find_by(user_id: current_user.id) %>
          <%= link_to "See received bids", move_bids_path(move.id), class: "small_button" %>
          <%= link_to "Edit", edit_move_path(move.id), class: "small_button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/moves/client_index.html.erb
<div class="container-full d-flex justify-content-end addmove">
  <%= link_to "Add a new move", new_move_path, class: "small_button" %>
</div>
<div class="container d-flex justify-content-center">
  <h1 class="moves-text">My  Moves</h1>
</div>
<div class="container d-flex justify-content-center mt-5">
  <h2>Good afternoon, <%= @user.first_name %>! 👋</h2>
</div>
<div class="container d-flex justify-content-center mb-5">
  <h2>Let's get Movin'</h2>
</div>
<% if @moves %>
  <div class="container d-flex justify-content-center">
    <h5>This is where your Moves live.</h5>
  </div>
  <div class="container d-flex justify-content-center">
    <h5>Don't forget to check their status!</h5>
  </div>
  <% if @next_move %>
    <h2 style="margin: 65px;">Next Move Coming Up:</h2>
    <div class="container jusfify-content-center d-flex">
      <div class="small-card mb-5 card popup" style="width: 540px;margin-left: 65px;" id="card-div"  data-controller="popup" data-popup-id-value="<%= @next_move.id %>">
        <div class="container d-flex" style="justify-content: space-between;">
          <div class="status-icon mb-3">
            <%if @next_move.status == "open"%>
              <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= @next_move.status %></h6>
            <%elsif @next_move.status == "pending"%>
              <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= @next_move.status %> </h6>
            <%else%>
              <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= @next_move.status %></h6>
            <%end%>
          </div>
          <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-times"></i>
          <% end%>
        </div>

          <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i>
            <%= @next_move.date.strftime("%d %b %Y") %></h5>
          <br>
          <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
            <%= @next_move.date.strftime("%l:%m %p") %></h5>
          <br>
          <h6>from</h6>
          <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
            <%= @next_move.start_point %></h5>
          <br>
          <h6 class="ml-1" >to</h6>
          <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= @next_move.end_point %></h5>

        <br>
        <div class="d-flex justify-content-between">
          <a href="#" data-action="click->popup#open" class="small_button">See details</a>
          <%= link_to "Edit", edit_move_path(@next_move.id), class: "small_button" %>
        </div>
        <div id="<%= @next_move.id %>" class="d-none">
          <%= render "show", move: @next_move %>
        </div>
      </div class="info mt-5 ">
      <% if @next_move.status=="open" %>
        <div style="width: 540px;padding: 122px;margin-left: 65px;">
          Your move is now published. Wait for companies to bid on it! Review the bids and hire the best company.
        </div>
      <% elsif @next_move.status=="pending" %>
        <div style="width: 540px;padding: 122px;margin-left: 65px;">
          You have now hired a company for your move. Now wait for the company to confirm that they are still available on that date!

        </div>
      <% else %>
        <div style="width: 540px;padding: 122px;margin-left: 65px;">
          The company has confirmed your move! Now relax and let them come pick up your stuff!
        </div>
      <%end  %>
    </div>
  <% else %>
    <h2 style="margin: 65px;">You have no moves yet! add a move!</h2>
  <% end %>
  <% if @moves %>
    <h2 style="margin: 65px;">Future Moves:</h2>
    <div class="container d-flex flex-wrap justify-content-between" >
      <% @moves.each do |move| %>
        <div class="small-card mb-5 card popup" style="width: 540px;" id="card-div"  data-controller="popup" data-popup-id-value="<%= move.id %>">
          <div class="container d-flex" style="justify-content: space-between;">
            <div class="status-icon mb-3">
              <%if move.status == "open"%>
                <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= move.status %></h6>
              <%elsif move.status == "pending"%>
                <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= move.status %> </h6>
              <%else %>
                <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= move.status %></h6>
              <%end%>
            </div>
            <% if !@next_move.nil? %>
              <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-times"></i>
              <% end%>
            <% end %>
          </div>
              <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i>
                <%= move.date.strftime("%d %b %Y") %></h5>
              <br>
            <div class= "d-flex justify-content-between ">
              <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
                <%= move.date.strftime("%l:%m %p") %></h5>
              <br>
              <div class= "d-flex position-absolute flex-column flex-wrap move-photo">
              <% if  move.bids.present? && move.bids.where("status = 'confirmed' OR status = 'pending'").count > 0 %>
                <div class="small-card" id="hiredcard">
                <h4 id="hired">You hired:</h4>
                <h5 ><i class="iconmove fa-solid fa-building " style="color: #f66b0e;"></i><%=  move.bids.where("status = 'confirmed' OR status = 'pending'").first.company.name  %> </h5>
                <h5 style="color: #f66b0e" >Bid price: <%=  move.bids.where("status = 'confirmed' OR status = 'pending'").first.price  %> € </h5>
                <%= image_tag "#{User.find(move.bids.where("status = 'confirmed' OR status = 'pending'").first.company.user_id).first_name}.jpg", class:"avatar-foto" %>
                </div>
              <% end %>
            </div>
          </div>
            <h6>from</h6>
            <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
              <%= move.start_point %></h5>
            <br>
            <h6 class="ml-1" >to</h6>
            <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= move.end_point %></h5>
          <br>

          <div class="d-flex justify-content-between">
            <a href="#" data-action="click->popup#open" class="small_button">See details</a>
            <%= link_to "Edit", edit_move_path(move.id), class: "small_button" %>
          </div>
          <div id="<%= move.id %>" class="d-none">
            <%= render "show", move: move %>
          </div>
        </div>
      <% end %>
    </div>
  <%end %>
<%end %>

app/views/moves/company_index.html.erb
<div class="container px-4" data-controller="search">
  <div class="centered-container mb-5">
    <h1>CHOOSE A MOVE AND PLACE A BID!</h1>
  </div>
  <div class="row gx-5" style="margin-bottom: 2%;">
    <div class="col" style="margin-left: 6%;">
  <%= form_with url: company_path, method: :get  do %>
     <div class="search-form search-form-control form-group p-3 ms-2" style="
    width: 520px;"> <%= text_field_tag :query,
          params[:query],
          class: "form-control search-form",
          placeholder: "Find the perfect move"%>
          <button name="button" type="submit" class="btn btn-flat" >
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
    <div class="col" style="margin-right: 2%;">
       <div class="filter-form simple_form p-3">
        <select class="search-form-control form-control ms-5 form-control-rounded" type="text" name="filter" id="search_query_filter" style="height: 49px;border-radius: 50px;">
          <option value="created">Recently posted</option>
          <option value="earliest">Earliest move</option>
        </select>
        <%# <button name="button" type="submit" class="btn btn-flat" style="position: absolute top: 2px;right: 2px;" >
          <i class="fa-solid fa-filter"></i>        </button> %>
      </div>
    </div>
   <%= link_to "See my Bids", bids_path(), class: "small_button" %>
  </div>
  <% end %>
  <div class="row gx-5">
    <%= render 'companies', moves: @moves, markers: @markers %>
  </div>
</div>

app/views/moves/show.html.erb
<div class="container-full d-flex justify-content-end addmove">
  <%= link_to "Add a new move", new_move_path, class: "small_button" %>
</div>
<h1>My move</h1>
<div class="container-full d-flex justify-content-center">
  <div class="container-full d-flex flex-wrap justify-content-center showcard">
    <div class="card col-8 mb-5">
      <div id="showcards" class="card-body d-flex flex-column justify-content-between">
        <h5 id="showcards" class="card-title"><i class="iconmove fa-solid fa-calendar" style="color: #f66b0e;"></i> Moving at: <%= Time.at(@move.date) %> UTC</h5>
        <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-location-pin" style="color: #f66b0e;"></i> From: <%= @move.start_point %></h5>
        <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-location-dot" style="color: #f66b0e;"></i>To: <%= @move.end_point %></h5>
        <h5 id="showcards" class="card-text"><i class="iconmove fa-solid fa-exclamation-circle" style="color: #f66b0e;"></i>Status: <%= @move.status %></h5>
        <div class="d-flex justify-content-between">
          
          <%= link_to "See received bids", move_bids_path(@move.id), class: "small_button" %>
          <%= link_to "Edit", edit_move_path(@move.id), class: "small_button" %>
          <%= link_to "", move_path(@move.id),  class: "order-3 btn btn-outline-danger text-light fa-solid fa-trash-can pt-2", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/moves/test.html.erb
<div class="container-full d-flex justify-content-end addmove">
  <%= link_to "Add a new move", new_move_path, class: "small_button" %>
</div>
<div class="container d-flex justify-content-center">
  <h1 class="moves-text">My published moves</h1>
</div>
<div class="container d-flex justify-content-center mt-5 mb-5">
  <h2>Hello <%= @user.nickname %> !</h2>
</div>
<% if @moves %>
<div class="container d-flex justify-content-center">
  <h5>Here are your published moves.</h5>
</div>
<div class="container d-flex justify-content-center">
  <h5>Check their status for the follow up!</h5>
</div>

<% if @next_move %>

<h2 style="margin: 65px;">Here is your next move!</h2>
<div class="container jusfify-content-center d-flex">
  <div class="small-card mb-5 card popup" style="width: 540px;margin-left: 65px;" id="card-div"  data-controller="popup" data-popup-id-value="<%= @next_move.id %>">
  <div class="container d-flex" style="justify-content: space-between;">
      <div class="status-icon mb-3">
        <%if @next_move.status == "open"%>
        <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= @next_move.status %></h6>
        <%elsif @next_move.status = "pending"%>
          <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= @next_move.status %> </h6>
        <%elsif @next_move.status = "confirmed"%>
          <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= @next_move.status %></h6>
        <%end%>
      </div>
            <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-times"></i>
            <% end%>
  </div>
      <%= link_to move_path(@next_move.id), data:{}, style:"text-decoration:none;", title: "show this @next_move" do %>
        <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i>
          <%= @next_move.date.strftime("%d %b %Y") %></h5>
        <br>
        <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
          <%= @next_move.date.strftime("%l:%m %p") %></h5>
        <br><h6>from</h6>
        <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
          <%= @next_move.start_point %></h5>
        <br><h6 class="ml-1" >to</h6>
        <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= @next_move.end_point %></h5>
      <% end %>
      <br>
      <div class="d-flex justify-content-between">
          <a href="#" data-action="click->popup#open" class="small_button">See details</a>
          <%= link_to "Edit", edit_move_path(@next_move.id), class: "small_button" %>
      </div>
      <div id="<%= @next_move.id %>" class="d-none">
        <%= render "show", move: @next_move %>
      </div>
  </div class="info mt-5 ">
  <% if @next_move.status=="open" %>
  <div style="width: 540px;padding: 122px;margin-left: 65px;">
    Your move is now published. Wait for companies to bid on it! Review the bids and hire the best company.
  </div>
  <% elsif @next_move.status=="pending" %>
  <div style="width: 540px;padding: 122px;margin-left: 65px;">
    You have now hired a company for your move. Now wait for the company to confirm that they are still available on that date!
  </div>
   <% else %>
  <div style="width: 540px;padding: 122px;margin-left: 65px;">
    The company has confirmed your move! Now relax and let them come pick up your stuff!
  </div>
  <%end  %>
</div>
<% else %>
<h2 style="margin: 65px;">You have no moves yet! add a move!</h2>
<% end %>


<% if @moves %>
<h2 style="margin: 65px;">Here are your other moves!</h2>
<div class="container d-flex flex-wrap justify-content-between" >
  <% @moves.each do |move| %>

    <div class="small-card mb-5 card popup" style="width: 540px;" id="card-div"  data-controller="popup" data-popup-id-value="<%= move.id %>">
        <div class="container d-flex" style="justify-content: space-between;">
          <div class="status-icon mb-3">
            <%if move.status == "open"%>
            <h6> <i class="fa-solid fa-arrow-rotate-right"></i> <%= move.status %></h6>
            <%elsif move.status = "pending"%>
              <h6> <i class="fa-solid fa-arrows-rotate fa-spin"> </i><%= move.status %> </h6>
            <%elsif move.status = "confirmed"%>
              <h6> <i class="fa-solid fa-square-check" style="color: #73c431;"> </i> <%= move.status %></h6>
            <%end%>
          </div>
          <%= link_to  move_path(@next_move.id), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-times"></i>
          <% end%>
    </div>
      <%= link_to move_path(move.id), data:{}, style:"text-decoration:none;", title: "show this move" do %>
        <h5 class="card-title"> <i class="fa-solid fa-calendar" style="color: #f66b0e"></i>
          <%= move.date.strftime("%d %b %Y") %></h5>
        <br>
        <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
          <%= move.date.strftime("%l:%m %p") %></h5>
        <br><h6>from</h6>
        <h5 class="card-title"> <i class="fa-solid fa-location-dot" style="color: #f66b0e"></i>
          <%= move.start_point %></h5>
        <br><h6 class="ml-1" >to</h6>
        <h5 class="card-title"> <i class="fa-solid fa-map-pin"></i> <%= move.end_point %></h5>
      <% end %>
      <br>
      <div class="d-flex justify-content-between">
          <a href="#" data-action="click->popup#open" class="small_button">See details</a>
          <%= link_to "Edit", edit_move_path(move.id), class: "small_button" %>
        </div>
    <div id="<%= move.id %>" class="d-none">
      <%= render "show", move: move %>
    </div>

    </div>
  <% end %>
</div>
<%end %>
<%end %>