config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/create", to: "moves#create_home"
  resources :moves do
    resources :bids, only: %i[new edit update  create index]
  end
  resources :bids, only: [:show]

  patch '/companies/bids', to: 'bids#confirm', as: 'confirm_bid'
  patch 'moves/:move_id/bids/:id/hire', to: 'bids#hire', as: 'hire_bid'
  get "/bids", to: "bids#index", as: "bids"
  get "/clients", to: "moves#client_index", as: "client"
  get "/companies", to: "moves#company_index", as: "company"
  get "/companies/bids", to: "bids#index", as: "company_bids"
  post "/update_bid_status", to: "bids#update_bid_status"
  resources :company do
    resources :reviews, only: %i[new create edit delete update]
  end
  get "/company/:id", to: "company#show", as: "company_show"
  resources :chatrooms, only: %i[new create show] do
    resources :messages, only: :create
  end
      resources :bids, only: %i[ delete]

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  # before_action :set_move, only: %i[show destroy]
  before_action :set_bid, only: %i[edit update destroy]

  def show
    @reviews = Review.where(company_id: params[:id])
    @company = Company.find_by(user_id: current_user.id)
    @bids = Bid.where(company_id: @company.id)
  end

  def new
    @bid = Bid.new
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.owner = current_user
    @bid.move = @move
    if @bid.save
      redirect_to move_bids_path, notice: 'moves was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @move = Move.find(params[:id])
  end

  def update
    if @bid.update(bid_params)
      redirect_to move_bids_path, notice: 'bid was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bid.destroy
    redirect_to move_bids_path, notice: 'bid was successfully destroyed.'
  end
end

  # def set_move
  #   @move = Move.find(params[:id])
  # end

#   def set_bid
#     @my_bid = Bid.find(params[:id])
#   end

  # def bid_params
  #   params.require(:bid).permit(:price, :status, :expiration)
  # end

app/views/company/show.html.erb
<h1>Hello <%= @company.name%></h1>
<div class="d-flex justify-content-center">
  <div class="small-card mb-5" id="card-div">
    <h5 class="card-title">
      <%= @company.name%></h5>
  <br>
  <h5 class="card-title"><i class="fa-regular fa-clock" style="color: #f66b0e"></i>
    <%= @company.address%></h5>
    <%= link_to "add a review", new_company_review_path(@company.id), class: "small_button_goal" %>
  </div>

</div>
  <% if @reviews %>
  <div class="container">
  <div>

    <h2>My reviews</h2>
      <div class="notifications">
      <% @reviews.each do |review| %>
          <div class="notification">
            <% user = User.find_by(id:review.client_id) %>
            <%= image_tag "#{user.first_name}.jpg", class:"avatar-foto" %>
            <div class="notification-content">
              <h6>Posted on <%= review.created_at %></h6>
              <p><%= review.content %></p>
            </div>
          </div>
      <%end%>
      </div>
      <%end%>
  </div>
</div>
</div>
  </div>